import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../controllers/auth_controller.dart';
import '../controllers/post_controller.dart';
import '../models/post_model.dart';
import '../providers/app_provider.dart';

class PostDetailsPage extends StatefulWidget {
  final PostModel post;
  const PostDetailsPage({required this.post, super.key});

  @override
  State<PostDetailsPage> createState() => _PostDetailsPageState();
}

class _PostDetailsPageState extends State<PostDetailsPage> {
  final _commentController = TextEditingController();

  void _addComment() async {
    if (_commentController.text.trim().isEmpty) return;
    
    final authController = Provider.of<AuthController>(context, listen: false);
    final postController = Provider.of<PostController>(context, listen: false);
    final user = authController.currentUser!;
    
    final newComment = CommentModel(
      id: '', // Will be generated by Firestore
      postId: widget.post.id,
      authorId: user.uid,
      authorName: user.name,
      authorProfileImage: user.profileImage,
      text: _commentController.text.trim(),
      createdAt: DateTime.now(),
    );
    
    await postController.addComment(newComment);
    _commentController.clear();
  }

  @override
  Widget build(BuildContext context) {
    final locale = AppLocalization.of(context)!;
    final postController = Provider.of<PostController>(context);

    return Scaffold(
      appBar: AppBar(title: Text(locale.translate('post_details'))),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              child: Column(
                children: [
                   // Post Content (Re-use PostCard structure for consistency)
                   _buildPostPlaceholder(widget.post),
                   const Divider(color: Colors.grey, thickness: 0.2),
                   // Comments Section
                   StreamBuilder<List<CommentModel>>(
                     stream: postController.getPostComments(widget.post.id),
                     builder: (context, snapshot) {
                       if (!snapshot.hasData || snapshot.data!.isEmpty) return const Padding(padding: EdgeInsets.all(20), child: Text('No comments yet.', style: TextStyle(color: Colors.grey)));
                       final comments = snapshot.data!;
                       return ListView.builder(
                         shrinkWrap: true,
                         physics: const NeverScrollableScrollPhysics(),
                         itemCount: comments.length,
                         itemBuilder: (context, index) {
                           final comment = comments[index];
                           return ListTile(
                             leading: CircleAvatar(backgroundImage: NetworkImage(comment.authorProfileImage)),
                             title: Text(comment.authorName, style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.white)),
                             subtitle: Column(
                               crossAxisAlignment: CrossAxisAlignment.start,
                               children: [
                                 Text(comment.text, style: const TextStyle(color: Colors.grey)),
                                 const SizedBox(height: 5),
                                 TextButton(onPressed: () {}, child: const Text('Reply', style: TextStyle(fontSize: 10))),
                               ],
                             ),
                           );
                         },
                       );
                     },
                   ),
                ],
              ),
            ),
          ),
          // Comment Input
          Container(
            padding: const EdgeInsets.all(10),
            color: const Color(0xFF16161A),
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _commentController,
                    style: const TextStyle(color: Colors.white),
                    decoration: InputDecoration(
                      hintText: locale.translate('add_comment_hint'),
                      hintStyle: const TextStyle(color: Colors.grey),
                      border: OutlineInputBorder(borderRadius: BorderRadius.circular(15)),
                    ),
                  ),
                ),
                IconButton(icon: const Icon(Icons.send, color: Colors.blue), onPressed: _addComment),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildPostPlaceholder(PostModel post) {
    return Padding(
      padding: const EdgeInsets.all(12.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              CircleAvatar(backgroundImage: NetworkImage(post.authorProfileImage)),
              const SizedBox(width: 10),
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(post.authorName, style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.white)),
                  Text(post.authorPosition, style: const TextStyle(color: Colors.grey, fontSize: 12)),
                ],
              ),
            ],
          ),
          const SizedBox(height: 10),
          Text(post.text, style: const TextStyle(color: Colors.white)),
        ],
      ),
    );
  }
}
